name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 2"

jobs:
  test:
    strategy:
      matrix:
        image: [ ubuntu, ubuntu-14.04, alpine, debian, amazonlinux, centos7, rockylinux8, rockylinux9, fedora]
    runs-on: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Test in ${{ matrix.image }}
        run: ./test.sh ${{ matrix.image }}